In [1]:
#GITHUB PROJECT 
#Ship Fuel Consumption & CO2 Emissions Analysis
#Data Cleaning

import pandas as pd
import numpy as np

raw_df = pd.read_csv('ship_fuel_efficiency.csv')
raw_df

,ship_id,ship_type,route_id,month,distance,fuel_type,fuel_consumption,CO2_emissions,weather_conditions,engine_efficiency
0,NG001,Oil Service Boat,Warri-Bonny,January,132.26,HFO,3779.77,10625.76,Stormy,92.14
1,NG001,Oil Service Boat,Port Harcourt-Lagos,February,128.52,HFO,4461.44,12779.73,Moderate,92.98
2,NG001,Oil Service Boat,Port Harcourt-Lagos,March,67.30,HFO,1867.73,5353.01,Calm,87.61
3,NG001,Oil Service Boat,Port Harcourt-Lagos,April,71.68,Diesel,2393.51,6506.52,Stormy,87.42
4,NG001,Oil Service Boat,Lagos-Apapa,May,134.32,HFO,4267.19,11617.03,Calm,85.61
...,...,...,...,...,...,...,...,...,...,...
1435,NG120,Fishing Trawler,Port Harcourt-Lagos,August,63.84,Diesel,1633.85,4852.28,Stormy,75.88
1436,NG120,Fishing Trawler,Lagos-Apapa,September,61.43,HFO,1263.48,3571.13,Calm,78.00
1437,NG120,Fishing Trawler,Port Harcourt-Lagos,October,193.09,HFO,4661.63,12267.13,Stormy,79.67
1438,NG120,Fishing Trawler,Lagos-Apapa,November,166.50,Diesel,4298.00,12297.71,Moderate,92.87
1439,NG120,Fishing Trawler,Warri-Bonny,December,127.66,Diesel,3549.91,10641.90,Moderate,90.82

In [5]:
raw_df.shape

(1440, 10)

In [7]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1440 entries, 0 to 1439
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ship_id             1440 non-null   object
 1   ship_type           1440 non-null   object
 2   route_id            1440 non-null   object
 3   month               1440 non-null   object
 4   distance            1440 non-null   float64
 5   fuel_type           1440 non-null   object
 6   fuel_consumption    1440 non-null   float64
 7   CO2_emissions       1440 non-null   float64
 8   weather_conditions  1440 non-null   object
 9   engine_efficiency   1440 non-null   float64
dtypes: float64(4), object(6)
memory usage: 112.6+ KB

In [9]:
#Kaθαρισμός δεδομένων απο διπλοτυπές τιμές 

raw_df.duplicated().sum()

0

In [11]:
#Eλεγχος τιμών να μην είναι αρνητικές ή μηδενικές

raw_df = raw_df [raw_df ['distance'] > 0]
raw_df = raw_df [raw_df ['fuel_consumption'] > 0]
raw_df  = raw_df [raw_df ['CO2_emissions'] > 0]
raw_df  = raw_df [(raw_df ['engine_efficiency'] >= 0) & (raw_df ['engine_efficiency'] <= 100)]

In [12]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1440 entries, 0 to 1439
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ship_id             1440 non-null   object
 1   ship_type           1440 non-null   object
 2   route_id            1440 non-null   object
 3   month               1440 non-null   object
 4   distance            1440 non-null   float64
 5   fuel_type           1440 non-null   object
 6   fuel_consumption    1440 non-null   float64
 7   CO2_emissions       1440 non-null   float64
 8   weather_conditions  1440 non-null   object
 9   engine_efficiency   1440 non-null   float64
dtypes: float64(4), object(6)
memory usage: 123.8+ KB

In [13]:
raw_df

,ship_id,ship_type,route_id,month,distance,fuel_type,fuel_consumption,CO2_emissions,weather_conditions,engine_efficiency
0,NG001,Oil Service Boat,Warri-Bonny,January,132.26,HFO,3779.77,10625.76,Stormy,92.14
1,NG001,Oil Service Boat,Port Harcourt-Lagos,February,128.52,HFO,4461.44,12779.73,Moderate,92.98
2,NG001,Oil Service Boat,Port Harcourt-Lagos,March,67.30,HFO,1867.73,5353.01,Calm,87.61
3,NG001,Oil Service Boat,Port Harcourt-Lagos,April,71.68,Diesel,2393.51,6506.52,Stormy,87.42
4,NG001,Oil Service Boat,Lagos-Apapa,May,134.32,HFO,4267.19,11617.03,Calm,85.61
...,...,...,...,...,...,...,...,...,...,...
1435,NG120,Fishing Trawler,Port Harcourt-Lagos,August,63.84,Diesel,1633.85,4852.28,Stormy,75.88
1436,NG120,Fishing Trawler,Lagos-Apapa,September,61.43,HFO,1263.48,3571.13,Calm,78.00
1437,NG120,Fishing Trawler,Port Harcourt-Lagos,October,193.09,HFO,4661.63,12267.13,Stormy,79.67
1438,NG120,Fishing Trawler,Lagos-Apapa,November,166.50,Diesel,4298.00,12297.71,Moderate,92.87
1439,NG120,Fishing Trawler,Warri-Bonny,December,127.66,Diesel,3549.91,10641.90,Moderate,90.82

In [14]:
raw_df.to_csv('ship_fuel_efficiency_cleaned.csv', index=False)